config/routes.rb
Rails.application.routes.draw do
  
  # ログイン、アカウント編集後、任意のページに推移させるための記述
  devise_for :users
  root to: "home#index"

  #サインアップページ「/users/sign_up」でエラーが発生した場合、「/users」にリダイレクトされるのを防ぐため
  #「devise_scope :users」以下の記述を追記して、任意のルーティングをさせています。
  devise_scope :user do
    get "/users", to: redirect("/users/sign_up")
  end
  
  namespace 'users' do #/users/が前にきます
    resource :account, only: [:show]
    resource :profile, only: [:show, :edit, :update]
  end

  #get "reservations/confirm" => "reservations#new"
  resources :reservations do
    collection do
      post "confirm", to:"reservations#confirm"
    end
  end

  resources :rooms do
    get :own, on: :collection
    get :search, on: :collection
  end

end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :checkin_date, presence: true
  validates :checkout_date, presence: true
  validates :number_of_people, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 1}
  validates :amount_of_price, presence: true
  validate :date_check

  def date_check
    return if checkin_date.blank? || checkout_date.blank?
    errors.add(:checkout_date, "(チェックアウト)はチェックイン以降の日付を選択してください" )if checkout_date < checkin_date
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  
  #予約済み一覧
  def index
    @reservations= current_user.reservations.all
  end

  def create #room/showからの、予約確定ボタンの先
    @reservation = current_user.reservations.new(reservation_params)
    if @reservation.save
      flash[:notice] = "予約を完了しました"
      redirect_to reservations_path
    else
      render confirm_reservations_path
      flash[:alert] = "予約に失敗しました"
    end
  end

  def edit
    @reservation = Reservation.find(params[:id])
  end


  def update
    @reservation = Reservation.find(params[:id])
    if @reservation.update(reservation_params)
      redirect_to reservations_path
    else
      render confirm_reservations_path
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    flash[:notice] = "予約を削除しました"
    redirect_to reservations_path
  end


  # 予約＆再予約 直前の内容確認
  def confirm
    
    # find_or_initialize_byはデータがあればとってくるなければ新しく初期化するというメソッド
    @reservation = current_user.reservations.find_or_initialize_by(id: params[:id])
    # editとnewで分岐させる(すでに作成されているreservationはroomが紐づいているので...)
    if @reservation.room.present?
      # 再予約の時はroomがすでに紐づいているので、@reservation.roomで呼び出す
      @room = @reservation.room
    else
      # 新規の時はまだ紐づく前なので、送られてきたroom_idからroomを特定する
      @room = Room.find(reservation_params[:room_id])
    end

    #@reservation.roomにそのif文で代入したroomを入れているということ
    @reservation.room = @room

    # edit newの共通の処理
    @reservation.checkin_date = reservation_params[:checkin_date]
    @reservation.checkout_date = reservation_params[:checkout_date]
    @reservation.number_of_people = reservation_params[:number_of_people].to_i
    # 宿泊日数の計算
    if reservation_params[:checkout_date].present? && reservation_params[:checkin_date].present?
      @reservation.length_of_stay = reservation_params[:checkout_date].to_date - reservation_params[:checkin_date].to_date
    end
    # 宿泊金額の合計計算
    @reservation.amount_of_price = @reservation.length_of_stay.to_i * @room.price.to_i * reservation_params[:number_of_people].to_i

    #「予約確定」押下前の確認画面でバリデーションメッセージを表示するため、以下を追加
    # reservationバリデ-ションが通らなかった時(unless)、中身のif文を実行 
    unless @reservation.valid?
      #id=DBが存在する＝予約編集
      if @reservation.id.present?
        render :edit
      #id=DBが存在しない＝新規予約
      else
        render 'rooms/show'
      end
    end
  end

  private

  def reservation_params
    params.require(:reservation).permit(:room_id, :user_id, :checkin_date, :checkout_date, :number_of_people, :length_of_stay, :amount_of_price)
  end
  
end

app/views/reservations/confirm.html.erb
<%= render "shared/error", obj: @reservation %>

<h2>予約内容の確認</h2>

<table>
  <thead>
    <tr>
      <th>チェックイン</th>
      <th>チェックアウト</th>
      <th>日数</th>
      <th>人数</th>
      <th>お支払い金額</th>
      <p>下記内容で正しければ「確定」ボタンを押してください。</p>
    </tr>
  </thead>
  
  <tbody>
    <%= form_with model: @reservation, local: true do |f| %>
      
      <!--createアクションpermitパラムスをhiddenでまとめて送る-->
      <%= f.hidden_field :room_id, value: @reservation.room_id %>
      <%= f.hidden_field :user_id, value: @reservation.user_id %>
      <%= f.hidden_field :checkin_date, value: @reservation.checkin_date %>
      <%= f.hidden_field :checkout_date, value: @reservation.checkout_date %>
      <%= f.hidden_field :length_of_stay, value: @reservation.length_of_stay %>
      <%= f.hidden_field :number_of_people, value: @reservation.number_of_people %>
      <%= f.hidden_field :amount_of_price, value: @reservation.amount_of_price %>

      <tr>
        <td><%= @reservation.checkin_date %></td>
        <td><%= @reservation.checkout_date %></td>
        <td><%= @reservation.length_of_stay %></td>
        <td><%= @reservation.number_of_people %></td>
        <td><%= @reservation.amount_of_price %></td>
      </tr>

      <div>
        <ul>
          <li><%= f.submit "予約を確定"%></li>
          <li><%= link_to "キャンセル", room_path(@reservation.room_id) %></li>
        </ul>
      </div>
      
    <% end %>
  </tbody> 
</table>

app/views/reservations/edit.html.erb
<%= render "shared/error", obj: @reservation %>

<h2><%="#{@reservation.room.name_of_hotel}"%>を再予約する</h2>

<%= form_with model: @reservation, url: confirm_reservations_path(id: @reservation.id), method: :post, local: true do |f| %>
  <%= hidden_field_tag :reservation_id, @reservation.id %>
    <table>
      <tr>
        <th><%= f.label :checkin_date, "チェックイン", class: "control-label" %></th>
        <td><%= f.date_field :checkin_date, class: "form-control" %></td>
      </tr>
      
      <tr>
        <th><%= f.label :checkout_date, "チェックアウト", class: "control-label" %></th>
        <td><%= f.date_field :checkout_date, class: "form-control" %></td>
      </tr>

      <tr>
        <th><%= f.label :number_of_people, "人数" %></th>
        <td><%= f.number_field :number_of_people, min: 1 %></td>
      </tr>
    </table>

    <div>
      <ul>
        <li><%= f.submit "再予約する"%></li>
        <li><%= link_to "キャンセル", :back %></li>
      </ul>
    </div>
<% end %>

app/views/reservations/index.html.erb
<h3>予約済み一覧</h3>

<table class="table">
  <thead>
    <tr>
      <th scope="col">画像</th>
      <th scope="col">施設名</th>
      <th scope="col">紹介文</th>
      <th scope="col">合計料金</th>
      <th scope="col">チェックイン</th>
      <th scope="col">チェックアウト</th>
      <th scope="col">予約確定日時</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td>
          <% if reservation.room.image .present?%>
            <%=image_tag reservation.room.image, size: '120x70' %>
          <%else%>
            <%= image_tag 'default-room-image.png', size: '120x70' %>
          <% end %>
        </td>
        <!--下記roomの詳細へのpathは、引数としてidを渡す必要あり。(reservation.room)-->
        <td><%= link_to "#{reservation.room.name_of_hotel}", room_path(reservation.room) %></td>
        <td><%= reservation.room.introduction %></td>
        <td><%= reservation.amount_of_price %></td>
        <td><%= reservation.checkin_date.strftime("%Y/%m/%d") %></td>
        <td><%= reservation.checkout_date.strftime("%Y/%m/%d") %></td>
        <td><%= reservation.created_at.strftime('%Y/%m/%d %H:%M') %></td>
        <td><%= link_to "再予約", edit_reservation_path(reservation.id) %></td>
        <td><%= link_to "予約を削除", reservation, method: :delete, data: { confirm: "本当に削除しますか？" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>