config/routes.rb
Rails.application.routes.draw do
  
  # ログイン、アカウント編集後、任意のページに推移させるための記述
  devise_for :users
  root to: "home#index"

  #サインアップページ「/users/sign_up」でエラーが発生した場合、「/users」にリダイレクトされるのを防ぐため
  #「devise_scope :users」以下の記述を追記して、任意のルーティングをさせています。
  devise_scope :user do
    get "/users", to: redirect("/users/sign_up")
  end
  
  namespace 'users' do #/users/が前にきます
    resource :account, only: [:show]
    resource :profile, only: [:show, :edit, :update]
  end

  #get "reservations/confirm" => "reservations#new"
  resources :reservations do
    collection do
      post "confirm", to:"reservations#confirm"
    end
  end

  resources :rooms do
    get :own, on: :collection
    get :search, on: :collection
  end

end

app/models/room.rb
class Room < ApplicationRecord

  belongs_to :user
  has_many :reservations
  #has_one_attachedメソッド記載したモデル各レコードは、各1つのファイルを添付可能
  has_one_attached :image

  #バリデーション(モデルの機能)
  validates :name_of_hotel, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :address, presence: true
  
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :check_update, only: [:update,:edit]
  
  def new
    @user = current_user
    @room = Room.new
  end

  def create
    @room = current_user.rooms.new(params.require(:room).permit(:image, :name_of_hotel, :introduction, :price, :address))
    if @room.save
      flash[:success] = "施設が作成されました"
      redirect_to @room
    else
      render new_room_path
      #flash[:alert] = "施設作成に失敗。施設画像以外は、記入必須項目です。"
    end
  end

  def show
    @user = current_user
    @room = Room.find(params[:id])
    #reservation(予約)を新規作成
    @reservation = Reservation.new
  end

  def edit
    @user = current_user
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])
    if @room.update (params.require(:room).permit(:image, :name_of_hotel, :introduction, :price, :created_at, :address))
      flash[:notice] = "「#{@room.name_of_hotel}」の情報を更新しました"
    redirect_to @room
    else
      render :edit
    end
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    flash[:notice] = "施設を削除しました"
    redirect_to :own_rooms
  end

  def own
    @rooms=current_user.rooms.all
  end

  def search
    @rooms = Room.all
    if params[:address].present?
      @rooms = @rooms.where('address LIKE ?', "%#{params[:address]}%")
    end
    if params[:keyword].present?
        @rooms = @rooms.where('address LIKE ?', "%#{params[:address]}%")
        @rooms = @rooms.where('name_of_hotel LIKE ? or introduction LIKE ?', "%#{params[:keyword]}%","%#{params[:keyword]}%")
    end
  end

  private

  def check_update
    if Room.find(params[:id]).user_id != current_user.id
      redirect_to root_path
    end
  end

end

app/views/rooms/edit.html.erb
<%= render "shared/error", obj: @room %>

<h2>施設情報の編集</h2>

<%= form_with model: @room do |f| %>
  <table>
    <tr>
      <th><%= f.label :name_of_hotel, "施設名" %></th>
      <td><%= f.text_field :name_of_hotel %></td>
    </tr>

    <tr>
      <th><%= f.label :introduction, "施設詳細" %></th>
      <td><%= f.text_area :introduction %></td>
    </tr>

    <tr>
      <th><%= f.label :price, "料金" %></th>
      <td><%= f.text_field :price %></td>
    </tr>

    <tr>
      <th><%= f.label :address, "住所" %></th>
      <td><%= f.text_field :address %></td>
    </tr>

    <tr>
      <th><%= f.label :image, "施設画像" %></th>
      <td><%= f.file_field :image, autofocus: true %></td>
    </tr>

  </table>

  <div>
    <ul>
      <li><%= f.submit "保存"%></li>
      <li><%= link_to "キャンセル", :own_rooms %></li>
    </ul>
  </div>
<% end %>

app/views/rooms/new.html.erb
<%= render "shared/error", obj: @room %>

<div class="row">
  <div class="col-md-6 offset-md-3">

    <h3>新規作成</h3>

    <%= form_with model: @room, local: true do |f| %>
      <table>
        <tr>
          <th><%= f.label :name_of_hotel, "施設名" %></th>
          <td><%= f.text_field :name_of_hotel %></td>
        </tr>

        <tr>
          <th><%= f.label :introduction, "施設詳細" %></th>
          <td><%= f.text_area :introduction %></td>
        </tr>

        <tr>
          <th><%= f.label :price, "料金" %></th>
          <td><%= f.text_field :price %></td>
        </tr>

        <tr>
          <th><%= f.label :address, "住所" %></th>
          <td><%= f.text_field :address %></td>
        </tr>

        <tr>
          <th><%= f.label :image, "施設画像" %></th>
          <td><%= f.file_field :image, autofocus: true %></td>
        </tr>
      </table>

      <div>
        <ul>
          <li><%= f.submit "保存"%></li>
          <li><%= link_to "キャンセル", :own_rooms %></li>
        </ul>
      </div>
    <% end %>

  </div>
</div>

app/views/rooms/own.html.erb
<h3>登録済み一覧</h3>

<% if flash[:success] %>
  <p class="success"><%= flash[:success] %></p>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th scope="col">画像</th>
      <th scope="col">施設名</th>
      <th scope="col">紹介文</th>
      <th scope="col">料金</th>
      <th scope="col">作成日</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  
  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td>
          <% if room.image.attached? %>
            <%= image_tag room.image, size: "120x70"%>
          <%else%>
            <%= image_tag 'default-room-image.png', size: "120x70"%>
          <% end %>
        </td>
        <td><%= link_to "#{room.name_of_hotel}", [room] %></td>
        <td><%= room.introduction %></td>
        <td>¥<%= room.price %>〜</td>
        <td><%= room.created_at.strftime('%Y/%m/%d') %></td>
        <td><%= link_to "編集", edit_room_path(room.id) %></td>
        <td><%= link_to "削除", room, method: :delete, data: { confirm: "本当に削除しますか？" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rooms/search.html.erb
<h1>検索</h1>
<%= form_with url: search_rooms_path, method: :get, local: true do |f| %>
  <%= f.text_field :address, :placeholder => "エリア名を入力"%>
  <%= f.text_field :keyword, :placeholder => "キーワード名を入力"%>
  <%= f.submit :search %>
<% end %>

<a><%= "#{@rooms.count}件が見つかりました。" %></a>

<table class="table">

  <thead>
    <tr>
      <th scope="col">画像</th>
      <th scope="col">施設名</th>
      <th scope="col">住所</th>
      <th scope="col"></th>
      <th scope="col">紹介文</th>
      <th scope="col">料金</th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td>
          <% if room.image.attached? %>
            <%= image_tag room.image, size: "120x70"%>
          <%else%>
            <%= image_tag 'default-room-image.png', size: "120x70"%>
          <% end %>
        </td>
        <td><%= link_to "#{room.name_of_hotel}", [room] %></td>
        <td><%= room.address %></td>
        <td>★★★★★</td>
        <td><%= room.introduction %></td>
        <td>¥<%= room.price %>〜</td>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/rooms/show.html.erb
<%= render "shared/error", obj: @reservation %>

<% if flash[:success] %>
  <p class="success"><%= flash[:success] %></p>
<% end %>

<p><%= link_to "←戻る", own_rooms_path %></p>
<% if current_user.id == @room.user_id %>
  <p><%= link_to "編集", edit_room_path(@room.id) %></p>
<% end %>

<div class ="container">

  <div class ="image_zone">
    <% if @room.image.attached? %>
      <%= image_tag @room.image, :size => '120x100'%>
    <%else%>
      <%= image_tag 'default-room-image.png' %>
    <% end %>
  </div>

  <div class ="details_of_hotel">
    <p><%= @room.name_of_hotel %></p>
    <p>¥<%= @room.price %>〜</p>
    <p>★★★★★</p>
    <p><%= @room.address %></p>
    <p><%= @room.introduction %></p>
  </div>

  <!--reservations/confirmへ-->
  <%= form_with model: @reservation, url: confirm_reservations_path(@reservation), local: true do |f| %>

    <%= f.hidden_field :room_id, value:@room.id %>
    <%= f.hidden_field :user_id, value:current_user.id %>

      <table>
        <tr>
          <th><%= f.label :checkin_date, "チェックイン", class: "control-label" %></th>
          <td><%= f.date_field :checkin_date, class: "form-control" %></td>
        </tr>

        <tr>
          <th><%= f.label :checkout_date, "チェックアウト", class: "control-label" %></th>
          <td><%= f.date_field :checkout_date, class: "form-control" %></td>
        </tr>

        <tr>
          <th><%= f.label :number_of_people, "人数" %></th>
          <td><%= f.number_field :number_of_people, min: 1 %></td>
        </tr>
      </table>

      <div>
        <ul>
          <li><%= f.submit "予約する"%></li>
        </ul>
      </div>
  <% end %>

</div>